// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwg6xmBRRO9r9VL78flRQR3E8ArpfU8ts',
    appId: '1:662599189677:web:1e558e939384da1ed27224',
    messagingSenderId: '662599189677',
    projectId: 'mynews-assignment',
    authDomain: 'mynews-assignment.firebaseapp.com',
    storageBucket: 'mynews-assignment.appspot.com',
    measurementId: 'G-VQSMJ9F8VY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDstUuGovzTGE4MgiVH2kX07FnP2edEj_U',
    appId: '1:662599189677:android:621629c059a0ac48d27224',
    messagingSenderId: '662599189677',
    projectId: 'mynews-assignment',
    storageBucket: 'mynews-assignment.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiULUwQXVV1-Die7ddx_LSdlHS7gSEml4',
    appId: '1:662599189677:ios:aa9c7d4ab15211d8d27224',
    messagingSenderId: '662599189677',
    projectId: 'mynews-assignment',
    storageBucket: 'mynews-assignment.appspot.com',
    iosBundleId: 'com.example.newsAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiULUwQXVV1-Die7ddx_LSdlHS7gSEml4',
    appId: '1:662599189677:ios:aa9c7d4ab15211d8d27224',
    messagingSenderId: '662599189677',
    projectId: 'mynews-assignment',
    storageBucket: 'mynews-assignment.appspot.com',
    iosBundleId: 'com.example.newsAssignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwg6xmBRRO9r9VL78flRQR3E8ArpfU8ts',
    appId: '1:662599189677:web:fbed6b75e4ede0f8d27224',
    messagingSenderId: '662599189677',
    projectId: 'mynews-assignment',
    authDomain: 'mynews-assignment.firebaseapp.com',
    storageBucket: 'mynews-assignment.appspot.com',
    measurementId: 'G-22WM53VXDE',
  );
}
